package com.baobei.job.executor.mapper.second;

import com.baobei.job.executor.domain.LeaderFeedback;
import java.util.List;

public interface LeaderFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_feedback
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_feedback
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    int insert(LeaderFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_feedback
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    LeaderFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_feedback
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    List<LeaderFeedback> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leader_feedback
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    int updateByPrimaryKey(LeaderFeedback record);
}