package com.baobei.job.executor.domain;

import java.io.Serializable;
import java.util.Date;

public class LeaderFeedback implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.id
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.aid
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private String aid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.sid
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.leader_name
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private String leaderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.signin_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private String signinImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.leader_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private String leaderImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.child_leader_insurance_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private String childLeaderInsuranceImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.white_book_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private String whiteBookImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.alltuu
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private Integer alltuu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.poster
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private Integer poster;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.remark
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.bus_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private String busImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.status
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.uid
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.nick_name
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.crt_time
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private Date crtTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leader_feedback.upd_time
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private Date updTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leader_feedback
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.id
     *
     * @return the value of leader_feedback.id
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.id
     *
     * @param id the value for leader_feedback.id
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.aid
     *
     * @return the value of leader_feedback.aid
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public String getAid() {
        return aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.aid
     *
     * @param aid the value for leader_feedback.aid
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setAid(String aid) {
        this.aid = aid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.sid
     *
     * @return the value of leader_feedback.sid
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.sid
     *
     * @param sid the value for leader_feedback.sid
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.leader_name
     *
     * @return the value of leader_feedback.leader_name
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public String getLeaderName() {
        return leaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.leader_name
     *
     * @param leaderName the value for leader_feedback.leader_name
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setLeaderName(String leaderName) {
        this.leaderName = leaderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.signin_img
     *
     * @return the value of leader_feedback.signin_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public String getSigninImg() {
        return signinImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.signin_img
     *
     * @param signinImg the value for leader_feedback.signin_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setSigninImg(String signinImg) {
        this.signinImg = signinImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.leader_img
     *
     * @return the value of leader_feedback.leader_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public String getLeaderImg() {
        return leaderImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.leader_img
     *
     * @param leaderImg the value for leader_feedback.leader_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setLeaderImg(String leaderImg) {
        this.leaderImg = leaderImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.child_leader_insurance_img
     *
     * @return the value of leader_feedback.child_leader_insurance_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public String getChildLeaderInsuranceImg() {
        return childLeaderInsuranceImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.child_leader_insurance_img
     *
     * @param childLeaderInsuranceImg the value for leader_feedback.child_leader_insurance_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setChildLeaderInsuranceImg(String childLeaderInsuranceImg) {
        this.childLeaderInsuranceImg = childLeaderInsuranceImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.white_book_img
     *
     * @return the value of leader_feedback.white_book_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public String getWhiteBookImg() {
        return whiteBookImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.white_book_img
     *
     * @param whiteBookImg the value for leader_feedback.white_book_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setWhiteBookImg(String whiteBookImg) {
        this.whiteBookImg = whiteBookImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.alltuu
     *
     * @return the value of leader_feedback.alltuu
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public Integer getAlltuu() {
        return alltuu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.alltuu
     *
     * @param alltuu the value for leader_feedback.alltuu
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setAlltuu(Integer alltuu) {
        this.alltuu = alltuu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.poster
     *
     * @return the value of leader_feedback.poster
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public Integer getPoster() {
        return poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.poster
     *
     * @param poster the value for leader_feedback.poster
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setPoster(Integer poster) {
        this.poster = poster;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.remark
     *
     * @return the value of leader_feedback.remark
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.remark
     *
     * @param remark the value for leader_feedback.remark
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.bus_img
     *
     * @return the value of leader_feedback.bus_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public String getBusImg() {
        return busImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.bus_img
     *
     * @param busImg the value for leader_feedback.bus_img
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setBusImg(String busImg) {
        this.busImg = busImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.status
     *
     * @return the value of leader_feedback.status
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.status
     *
     * @param status the value for leader_feedback.status
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.uid
     *
     * @return the value of leader_feedback.uid
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.uid
     *
     * @param uid the value for leader_feedback.uid
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.nick_name
     *
     * @return the value of leader_feedback.nick_name
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.nick_name
     *
     * @param nickName the value for leader_feedback.nick_name
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.crt_time
     *
     * @return the value of leader_feedback.crt_time
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.crt_time
     *
     * @param crtTime the value for leader_feedback.crt_time
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leader_feedback.upd_time
     *
     * @return the value of leader_feedback.upd_time
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public Date getUpdTime() {
        return updTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leader_feedback.upd_time
     *
     * @param updTime the value for leader_feedback.upd_time
     *
     * @mbg.generated Wed Dec 05 17:58:33 CST 2018
     */
    public void setUpdTime(Date updTime) {
        this.updTime = updTime;
    }
}