package com.baobei.job.executor.mapper.first;

import com.baobei.job.executor.domain.HelpTopic;
import java.util.List;

public interface HelpTopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Fri Dec 07 17:23:33 CST 2018
     */
    int deleteByPrimaryKey(Integer helpTopicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Fri Dec 07 17:23:33 CST 2018
     */
    int insert(HelpTopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Fri Dec 07 17:23:33 CST 2018
     */
    HelpTopic selectByPrimaryKey(Integer helpTopicId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Fri Dec 07 17:23:33 CST 2018
     */
    List<HelpTopic> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table help_topic
     *
     * @mbg.generated Fri Dec 07 17:23:33 CST 2018
     */
    int updateByPrimaryKey(HelpTopic record);
}